### ISSUE TITLE
Possibly inaccurate information about `grid-area` in the README

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/css-grid-lab#4]
At the end of the "**`grid-column`**, **`grid-row`** and **`grid-area`**" section, the README says:

> Remember how it is possible to give names to lines using our `grid-template` properties? This is where these names become useful. If we had names for the beginning and end rows of a page footer, for instance, we could declare a `grid-area` for our footer as:
> 
> `grid-area: footer-start / 1 / footer-end / 4`

> This would start our area wherever the line `footer-start` is defined in our row template, and end wherever `footer-end` is defined. In a complex grid, taking the time to name important lines in your layout makes it easier to position grid elements to them without having to look up or count the number of lines.

I tried out something similar, but with `header-start` and `header-end` (which were used earlier in the README). I didn't see any changes when I refreshed the `index.html` page.

I think that line of code needs to be changed to `grid-area: footer`. I found a related tutorial from the MDN documentation that goes into this: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines#Implicit_grid_areas_from_named_lines

Hope that helps!

Sdcrouse

**Comment by lizbur10** [comment]
Closing as outdated
